2024-03-04 10:41:32,232 INFO    StreamThr :365016 [internal.py:wandb_internal():86] W&B internal server running at pid: 365016, started at: 2024-03-04 10:41:32.230087
2024-03-04 10:41:32,233 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status
2024-03-04 10:41:32,237 INFO    WriterThread:365016 [datastore.py:open_for_write():87] open: .\wandb\run-20240304_104132-yn7t1x8f\run-yn7t1x8f.wandb
2024-03-04 10:41:32,238 DEBUG   SenderThread:365016 [sender.py:send():382] send: header
2024-03-04 10:41:32,311 DEBUG   SenderThread:365016 [sender.py:send():382] send: run
2024-03-04 10:41:32,313 INFO    SenderThread:365016 [sender.py:_maybe_setup_resume():763] checking resume status for None/UNet-DAS/yn7t1x8f
2024-03-04 10:41:34,451 INFO    SenderThread:365016 [dir_watcher.py:__init__():211] watching files in: .\wandb\run-20240304_104132-yn7t1x8f\files
2024-03-04 10:41:34,451 INFO    SenderThread:365016 [sender.py:_start_run_threads():1136] run started: yn7t1x8f with start time 1709520092.232088
2024-03-04 10:41:34,471 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: check_version
2024-03-04 10:41:34,472 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: check_version
2024-03-04 10:41:36,396 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: run_start
2024-03-04 10:41:36,451 DEBUG   HandlerThread:365016 [system_info.py:__init__():27] System info init
2024-03-04 10:41:36,451 DEBUG   HandlerThread:365016 [system_info.py:__init__():42] System info init done
2024-03-04 10:41:36,451 INFO    HandlerThread:365016 [system_monitor.py:start():194] Starting system monitor
2024-03-04 10:41:36,451 INFO    SystemMonitor:365016 [system_monitor.py:_start():158] Starting system asset monitoring threads
2024-03-04 10:41:36,452 INFO    HandlerThread:365016 [system_monitor.py:probe():214] Collecting system info
2024-03-04 10:41:36,491 INFO    SystemMonitor:365016 [interfaces.py:start():190] Started cpu monitoring
2024-03-04 10:41:36,492 INFO    SystemMonitor:365016 [interfaces.py:start():190] Started disk monitoring
2024-03-04 10:41:36,492 INFO    SystemMonitor:365016 [interfaces.py:start():190] Started gpu monitoring
2024-03-04 10:41:36,530 INFO    SystemMonitor:365016 [interfaces.py:start():190] Started memory monitoring
2024-03-04 10:41:36,646 DEBUG   HandlerThread:365016 [system_info.py:probe():151] Probing system
2024-03-04 10:41:36,646 INFO    SystemMonitor:365016 [interfaces.py:start():190] Started network monitoring
2024-03-04 10:41:36,649 DEBUG   HandlerThread:365016 [system_info.py:_probe_git():136] Probing git
2024-03-04 10:41:36,776 DEBUG   HandlerThread:365016 [system_info.py:_probe_git():144] Probing git done
2024-03-04 10:41:36,777 DEBUG   HandlerThread:365016 [system_info.py:probe():199] Probing system done
2024-03-04 10:41:36,777 DEBUG   HandlerThread:365016 [system_monitor.py:probe():223] {'os': 'Windows-10-10.0.22631-SP0', 'python': '3.8.18', 'heartbeatAt': '2024-03-04T02:41:36.646883', 'startedAt': '2024-03-04T02:41:32.220087', 'docker': None, 'cuda': None, 'args': ('--batch_size', '64', '--lr', '1e-4'), 'state': 'running', 'program': 'main.py', 'codePathLocal': 'main.py', 'codePath': 'main.py', 'git': {'remote': 'git@github.com:/shahwaiz-git/NLOS-PA.git', 'commit': 'ef8a1b5b13f7ac3d414c0de126def03704c301b3'}, 'email': '1908657939@qq.com', 'root': 'D:/HISLab/毕设/CODE', 'host': 'Shahwaiz', 'username': '19086', 'executable': 'E:\\Anaconda\\envs\\unet\\python.exe', 'cpu_count': 8, 'cpu_count_logical': 16, 'cpu_freq': {'current': 3201.0, 'min': 0.0, 'max': 3201.0}, 'cpu_freq_per_core': [{'current': 3201.0, 'min': 0.0, 'max': 3201.0}], 'disk': {'/': {'total': 246.99901962280273, 'used': 137.7162208557129}}, 'gpu': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'gpu_count': 1, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3060 Laptop GPU', 'memory_total': 6442450944}], 'memory': {'total': 15.247127532958984}}
2024-03-04 10:41:36,777 INFO    HandlerThread:365016 [system_monitor.py:probe():224] Finished collecting system info
2024-03-04 10:41:36,777 INFO    HandlerThread:365016 [system_monitor.py:probe():227] Publishing system info
2024-03-04 10:41:36,777 DEBUG   HandlerThread:365016 [system_info.py:_save_conda():208] Saving list of conda packages installed into the current environment
2024-03-04 10:41:37,498 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20240304_104132-yn7t1x8f\files\conda-environment.yaml
2024-03-04 10:41:41,035 DEBUG   HandlerThread:365016 [system_info.py:_save_conda():220] Saving conda packages done
2024-03-04 10:41:41,036 INFO    HandlerThread:365016 [system_monitor.py:probe():229] Finished publishing system info
2024-03-04 10:41:41,043 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:41:41,044 DEBUG   SenderThread:365016 [sender.py:send():382] send: files
2024-03-04 10:41:41,044 INFO    SenderThread:365016 [sender.py:_save_file():1403] saving file wandb-metadata.json with policy now
2024-03-04 10:41:41,052 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: python_packages
2024-03-04 10:41:41,053 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: python_packages
2024-03-04 10:41:41,053 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:41:41,054 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:41:41,055 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:41:41,614 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_modified():288] file/dir modified: .\wandb\run-20240304_104132-yn7t1x8f\files\conda-environment.yaml
2024-03-04 10:41:41,615 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20240304_104132-yn7t1x8f\files\wandb-metadata.json
2024-03-04 10:41:41,615 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20240304_104132-yn7t1x8f\files\requirements.txt
2024-03-04 10:41:42,283 DEBUG   SenderThread:365016 [sender.py:send():382] send: telemetry
2024-03-04 10:41:42,283 DEBUG   SenderThread:365016 [sender.py:send():382] send: metric
2024-03-04 10:41:42,283 DEBUG   SenderThread:365016 [sender.py:send():382] send: telemetry
2024-03-04 10:41:42,283 DEBUG   SenderThread:365016 [sender.py:send():382] send: metric
2024-03-04 10:41:42,284 WARNING SenderThread:365016 [sender.py:send_metric():1354] Seen metric with glob (shouldn't happen)
2024-03-04 10:41:42,285 DEBUG   SenderThread:365016 [sender.py:send():382] send: config
2024-03-04 10:41:42,387 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:41:42,388 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:41:42,388 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:41:42,669 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_created():271] file/dir created: .\wandb\run-20240304_104132-yn7t1x8f\files\output.log
2024-03-04 10:41:43,298 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:41:44,045 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:41:44,045 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:41:44,045 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:41:44,715 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_modified():288] file/dir modified: .\wandb\run-20240304_104132-yn7t1x8f\files\output.log
2024-03-04 10:41:46,942 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:41:46,942 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:41:46,942 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:41:46,942 INFO    wandb-upload_0:365016 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\wandb\sdk\lib\retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2789, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "E:\Anaconda\envs\unet\lib\site-packages\wandb\sdk\internal\internal_api.py", line 2758, in upload_file
    response = self._upload_file_session.put(
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-04 10:41:47,061 ERROR   memory    :365016 [interfaces.py:monitor():144] Failed to sample metric: [WinError 1450] 系统资源不足，无法完成请求的服务。
2024-03-04 10:41:48,335 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:41:51,223 ERROR   memory    :365016 [interfaces.py:monitor():144] Failed to sample metric: [WinError 1450] 系统资源不足，无法完成请求的服务。
2024-03-04 10:41:51,238 ERROR   memory    :365016 [interfaces.py:monitor():144] Failed to sample metric: [WinError 1450] 系统资源不足，无法完成请求的服务。
2024-03-04 10:41:52,261 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:41:52,261 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:41:52,261 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:41:53,399 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:41:56,058 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:41:56,058 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:41:56,058 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:41:58,493 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:01,845 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:42:01,846 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:42:01,846 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:42:03,545 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:04,331 INFO    Thread-16 :365016 [dir_watcher.py:_on_file_modified():288] file/dir modified: .\wandb\run-20240304_104132-yn7t1x8f\files\config.yaml
2024-03-04 10:42:09,021 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:11,061 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:42:11,062 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:42:11,062 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:42:14,584 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:19,635 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:21,305 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:42:21,305 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:42:21,305 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:42:24,711 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:26,066 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:42:26,081 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:42:26,082 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:42:30,547 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:35,704 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:36,651 DEBUG   SystemMonitor:365016 [system_monitor.py:_start():172] Starting system metrics aggregation loop
2024-03-04 10:42:36,665 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:42:40,712 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:41,077 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:42:41,092 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:42:41,093 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:42:46,218 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:51,236 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:42:55,030 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:42:55,030 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:42:55,031 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:42:56,092 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:42:56,148 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:42:56,190 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:42:56,515 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:01,556 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:06,612 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:06,667 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:43:11,107 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:43:11,107 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:43:11,108 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:43:12,512 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:17,535 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:22,580 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:26,098 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:43:26,112 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:43:26,112 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:43:28,490 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:33,550 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:36,672 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:43:38,697 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:41,110 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:43:41,139 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:43:41,140 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:43:44,620 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:49,696 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:54,723 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:43:56,124 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:43:56,154 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:43:56,155 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:44:00,574 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:05,584 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:06,675 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:44:10,716 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:11,125 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:44:11,169 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:44:11,170 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:44:13,174 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2765] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/yn7t1x8f/wandb-metadata.json?Expires=1709606501&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=c10cWzzWB0WTIdtcNahyGCw5ZVIoMtGmhBgqlfmcTHqU6IU1Fb9%2BeKYSxi5NVNaft0l7kFJxoEVHt9tJe3ESFt0Jjx5JIEd88ZWnP61i7iTdGUyjVnHW0uwRUZL7sdIBC7ujBnAwpzKxt53%2Bzz33bLVlB2UXO3EzoTRSzh4QDrugItjgg%2FWSGr7PWPYirP2D0FFIrYw%2BSxgHRXfTFYknVK9zeJse62LS2XRpL1l5QME3NbRGm1x3YvwxY6LYKFo2V5NYr3kJRtNm2BjQegyonvq3sMn7r4CmCY2iQjGHUbg%2B9CIO1ZjPLKMiRlWbjVweinPaZGZJpHAEYQtsPwa0Bw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-04 10:44:13,174 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2767] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1460'}
2024-03-04 10:44:13,174 ERROR   wandb-upload_0:365016 [internal_api.py:upload_file():2769] upload_file response body: 
2024-03-04 10:44:16,657 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:21,709 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:26,131 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:44:26,176 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:44:26,176 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:44:27,604 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:32,708 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:36,689 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:44:38,709 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:41,133 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:44:41,178 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:44:41,179 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:44:44,619 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:49,727 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:54,817 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:44:56,147 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:44:56,178 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:44:56,179 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:45:00,587 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:05,639 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:06,699 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:45:10,729 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:11,151 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:45:11,196 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:45:11,197 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:45:16,696 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:21,812 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:26,160 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:45:26,191 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:45:26,191 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:45:27,525 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:32,622 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:36,710 DEBUG   SenderThread:365016 [sender.py:send():382] send: stats
2024-03-04 10:45:37,724 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
2024-03-04 10:45:41,164 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: internal_messages
2024-03-04 10:45:41,210 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: stop_status
2024-03-04 10:45:41,210 DEBUG   SenderThread:365016 [sender.py:send_request():409] send_request: stop_status
2024-03-04 10:45:43,594 DEBUG   HandlerThread:365016 [handler.py:handle_request():146] handle_request: status_report
