2024-03-06 17:08:47,726 INFO    MainThread:71912 [internal.py:wandb_internal():90] W&B internal server running at pid: 71912, started at: 2024-03-06 17:08:47.725294
2024-03-06 17:08:47,729 INFO    WriterThread:71912 [datastore.py:open_for_write():75] open: .\wandb\run-20240306_170845-1d84l4sh\run-1d84l4sh.wandb
2024-03-06 17:08:47,735 DEBUG   SenderThread:71912 [sender.py:send():235] send: header
2024-03-06 17:08:47,735 DEBUG   SenderThread:71912 [sender.py:send():235] send: run
2024-03-06 17:08:47,739 INFO    SenderThread:71912 [sender.py:_maybe_setup_resume():492] checking resume status for None/UNet-DAS/1d84l4sh
2024-03-06 17:08:53,611 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: check_version
2024-03-06 17:08:53,624 INFO    SenderThread:71912 [dir_watcher.py:__init__():205] watching files in: .\wandb\run-20240306_170845-1d84l4sh\files
2024-03-06 17:08:53,624 INFO    SenderThread:71912 [sender.py:_start_run_threads():812] run started: 1d84l4sh with start time 1709716126
2024-03-06 17:08:53,624 DEBUG   SenderThread:71912 [sender.py:send():235] send: summary
2024-03-06 17:08:53,625 INFO    SenderThread:71912 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:08:53,626 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: check_version
2024-03-06 17:08:54,591 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: run_start
2024-03-06 17:08:54,620 DEBUG   HandlerThread:71912 [meta.py:__init__():35] meta init
2024-03-06 17:08:54,620 DEBUG   HandlerThread:71912 [meta.py:__init__():49] meta init done
2024-03-06 17:08:54,620 DEBUG   HandlerThread:71912 [meta.py:probe():209] probe
2024-03-06 17:08:54,635 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170845-1d84l4sh\files\wandb-summary.json
2024-03-06 17:08:54,639 DEBUG   HandlerThread:71912 [meta.py:_setup_git():199] setup git
2024-03-06 17:08:54,828 DEBUG   HandlerThread:71912 [meta.py:_setup_git():206] setup git done
2024-03-06 17:08:54,828 DEBUG   HandlerThread:71912 [meta.py:_save_pip():53] save pip
2024-03-06 17:08:54,830 DEBUG   HandlerThread:71912 [meta.py:_save_pip():67] save pip done
2024-03-06 17:08:54,830 DEBUG   HandlerThread:71912 [meta.py:_save_conda():74] save conda
2024-03-06 17:08:55,641 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170845-1d84l4sh\files\conda-environment.yaml
2024-03-06 17:08:55,642 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170845-1d84l4sh\files\requirements.txt
2024-03-06 17:08:58,680 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170845-1d84l4sh\files\conda-environment.yaml
2024-03-06 17:08:58,685 DEBUG   HandlerThread:71912 [meta.py:_save_conda():84] save conda done
2024-03-06 17:08:58,686 DEBUG   HandlerThread:71912 [meta.py:probe():247] probe done
2024-03-06 17:08:58,699 DEBUG   SenderThread:71912 [sender.py:send():235] send: files
2024-03-06 17:08:58,699 INFO    SenderThread:71912 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2024-03-06 17:08:58,709 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:08:58,711 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:08:59,691 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170845-1d84l4sh\files\wandb-metadata.json
2024-03-06 17:08:59,692 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170845-1d84l4sh\files\output.log
2024-03-06 17:09:00,024 DEBUG   SenderThread:71912 [sender.py:send():235] send: telemetry
2024-03-06 17:09:00,024 DEBUG   SenderThread:71912 [sender.py:send():235] send: metric
2024-03-06 17:09:00,024 DEBUG   SenderThread:71912 [sender.py:send():235] send: telemetry
2024-03-06 17:09:00,025 DEBUG   SenderThread:71912 [sender.py:send():235] send: metric
2024-03-06 17:09:00,025 WARNING SenderThread:71912 [sender.py:send_metric():905] Seen metric with glob (shouldn't happen)
2024-03-06 17:09:00,025 DEBUG   SenderThread:71912 [sender.py:send():235] send: config
2024-03-06 17:09:00,606 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:09:00,606 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:09:00,607 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:09:01,708 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170845-1d84l4sh\files\output.log
2024-03-06 17:09:02,277 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:09:02,277 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:09:02,278 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:09:05,046 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:09:05,046 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:09:05,047 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:09:05,047 ERROR   Thread-22 :71912 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 17:09:10,299 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:09:10,299 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:09:10,299 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:09:15,040 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:09:15,040 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:09:16,846 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170845-1d84l4sh\files\output.log
2024-03-06 17:09:18,955 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:09:18,956 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:09:18,956 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:09:19,872 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170845-1d84l4sh\files\config.yaml
2024-03-06 17:09:25,709 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:09:31,411 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:09:31,412 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:09:36,730 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:09:36,730 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:09:36,731 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:09:47,724 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:09:47,724 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:09:58,825 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:10:04,109 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:10:04,110 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:10:10,465 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:10:10,465 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:10:10,465 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:10:20,512 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:10:20,513 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:10:32,048 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:10:36,657 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:10:36,657 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:10:52,938 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:10:52,939 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:11:05,154 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:11:09,308 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:11:09,309 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:11:23,318 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:11:23,318 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:11:23,318 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:11:26,442 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:11:26,443 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:11:38,206 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:11:42,798 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:11:42,798 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:12:00,657 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:12:00,658 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:12:11,341 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:12:16,939 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:12:16,939 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:12:33,262 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:12:33,263 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:12:44,472 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:12:49,545 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:12:49,545 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:13:06,651 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:13:06,652 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:13:17,467 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:13:22,955 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:13:22,956 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:13:37,896 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/1d84l4sh/wandb-metadata.json?Expires=1709802540&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=AV54zfsRtt8M3Dw4%2BJSXc5gkkJLpZUoN7R6AuXMyiNGJPb1l9ff9LYNoHtJkHf23LG3nksdGQpyspXe2fEc7yNZX41LLWjolbSUT5Y5FrR4LypU7XwTDj8IfXxjJC1p9I5e6z%2FUjBHeFjCuBA4WfS8w8OWpyGxsiZRlhOOid2Knge2fYLHm%2FOeSm%2B8jSWCpPu0V99oZXRp5zRp7Zql13O%2FbEWsSg2OTgZ2hiVPERwObgySiMqWK1Utw3rNPq9sZdscyUE4gG8R9f2lZap4I8XXgXRh6xYjVKJZzErtaI5x80m2munmAgn%2Fo%2B2TOyHccsT6n7AkmaGtB77nKxbpdrtA%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:13:37,896 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:13:37,896 ERROR   Thread-22 :71912 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:13:39,340 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:13:39,340 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:13:50,648 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:13:55,657 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:13:55,658 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:14:12,057 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:14:12,058 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:14:20,785 WARNING MainThread:71912 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-03-06 17:14:21,744 DEBUG   SenderThread:71912 [sender.py:send():235] send: telemetry
2024-03-06 17:14:22,121 DEBUG   SenderThread:71912 [sender.py:send():235] send: exit
2024-03-06 17:14:22,121 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:14:22,121 INFO    SenderThread:71912 [sender.py:send_exit():371] handling exit code: 0
2024-03-06 17:14:22,121 INFO    SenderThread:71912 [sender.py:send_exit():373] handling runtime: 327
2024-03-06 17:14:22,122 INFO    SenderThread:71912 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:14:22,122 INFO    SenderThread:71912 [sender.py:send_exit():379] send defer
2024-03-06 17:14:22,122 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:14:22,123 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:14:22,123 INFO    HandlerThread:71912 [handler.py:handle_request_defer():164] handle defer: 0
2024-03-06 17:14:22,123 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: defer
2024-03-06 17:14:22,123 INFO    SenderThread:71912 [sender.py:send_request_defer():388] handle sender defer: 0
2024-03-06 17:14:22,123 INFO    SenderThread:71912 [sender.py:transition_state():392] send defer: 1
2024-03-06 17:14:22,124 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:14:22,124 INFO    HandlerThread:71912 [handler.py:handle_request_defer():164] handle defer: 1
2024-03-06 17:14:22,295 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:14:22,296 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: defer
2024-03-06 17:14:22,296 INFO    SenderThread:71912 [sender.py:send_request_defer():388] handle sender defer: 1
2024-03-06 17:14:22,296 INFO    SenderThread:71912 [sender.py:transition_state():392] send defer: 2
2024-03-06 17:14:22,296 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:14:22,297 DEBUG   SenderThread:71912 [sender.py:send():235] send: stats
2024-03-06 17:14:22,297 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:14:22,297 INFO    HandlerThread:71912 [handler.py:handle_request_defer():164] handle defer: 2
2024-03-06 17:14:22,298 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: defer
2024-03-06 17:14:22,298 INFO    SenderThread:71912 [sender.py:send_request_defer():388] handle sender defer: 2
2024-03-06 17:14:22,298 INFO    SenderThread:71912 [sender.py:transition_state():392] send defer: 3
2024-03-06 17:14:22,298 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:14:22,298 INFO    HandlerThread:71912 [handler.py:handle_request_defer():164] handle defer: 3
2024-03-06 17:14:22,298 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: defer
2024-03-06 17:14:22,299 INFO    SenderThread:71912 [sender.py:send_request_defer():388] handle sender defer: 3
2024-03-06 17:14:22,299 INFO    SenderThread:71912 [sender.py:transition_state():392] send defer: 4
2024-03-06 17:14:22,299 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:14:22,299 INFO    HandlerThread:71912 [handler.py:handle_request_defer():164] handle defer: 4
2024-03-06 17:14:22,299 DEBUG   SenderThread:71912 [sender.py:send():235] send: summary
2024-03-06 17:14:22,300 INFO    SenderThread:71912 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:14:22,300 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: defer
2024-03-06 17:14:22,300 INFO    SenderThread:71912 [sender.py:send_request_defer():388] handle sender defer: 4
2024-03-06 17:14:22,300 INFO    SenderThread:71912 [sender.py:transition_state():392] send defer: 5
2024-03-06 17:14:22,301 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:14:22,301 INFO    HandlerThread:71912 [handler.py:handle_request_defer():164] handle defer: 5
2024-03-06 17:14:22,301 DEBUG   SenderThread:71912 [sender.py:send_request():249] send_request: defer
2024-03-06 17:14:22,301 INFO    SenderThread:71912 [sender.py:send_request_defer():388] handle sender defer: 5
2024-03-06 17:14:22,410 DEBUG   HandlerThread:71912 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:14:22,550 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170845-1d84l4sh\files\output.log
2024-03-06 17:14:22,551 INFO    Thread-16 :71912 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170845-1d84l4sh\files\wandb-summary.json
