2024-03-06 17:05:33,643 INFO    MainThread:71340 [internal.py:wandb_internal():90] W&B internal server running at pid: 71340, started at: 2024-03-06 17:05:33.642790
2024-03-06 17:05:33,646 INFO    WriterThread:71340 [datastore.py:open_for_write():75] open: .\wandb\run-20240306_170531-2igzsq6a\run-2igzsq6a.wandb
2024-03-06 17:05:33,653 DEBUG   SenderThread:71340 [sender.py:send():235] send: header
2024-03-06 17:05:33,653 DEBUG   SenderThread:71340 [sender.py:send():235] send: run
2024-03-06 17:05:33,657 INFO    SenderThread:71340 [sender.py:_maybe_setup_resume():492] checking resume status for None/UNet-DAS/2igzsq6a
2024-03-06 17:05:38,059 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: check_version
2024-03-06 17:05:38,095 INFO    SenderThread:71340 [dir_watcher.py:__init__():205] watching files in: .\wandb\run-20240306_170531-2igzsq6a\files
2024-03-06 17:05:38,096 INFO    SenderThread:71340 [sender.py:_start_run_threads():812] run started: 2igzsq6a with start time 1709715932
2024-03-06 17:05:38,096 DEBUG   SenderThread:71340 [sender.py:send():235] send: summary
2024-03-06 17:05:38,096 INFO    SenderThread:71340 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:05:38,097 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: check_version
2024-03-06 17:05:38,908 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: run_start
2024-03-06 17:05:38,937 DEBUG   HandlerThread:71340 [meta.py:__init__():35] meta init
2024-03-06 17:05:38,937 DEBUG   HandlerThread:71340 [meta.py:__init__():49] meta init done
2024-03-06 17:05:38,938 DEBUG   HandlerThread:71340 [meta.py:probe():209] probe
2024-03-06 17:05:38,950 DEBUG   HandlerThread:71340 [meta.py:_setup_git():199] setup git
2024-03-06 17:05:39,104 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170531-2igzsq6a\files\wandb-summary.json
2024-03-06 17:05:39,134 DEBUG   HandlerThread:71340 [meta.py:_setup_git():206] setup git done
2024-03-06 17:05:39,135 DEBUG   HandlerThread:71340 [meta.py:_save_pip():53] save pip
2024-03-06 17:05:39,136 DEBUG   HandlerThread:71340 [meta.py:_save_pip():67] save pip done
2024-03-06 17:05:39,136 DEBUG   HandlerThread:71340 [meta.py:_save_conda():74] save conda
2024-03-06 17:05:40,113 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170531-2igzsq6a\files\requirements.txt
2024-03-06 17:05:40,114 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170531-2igzsq6a\files\conda-environment.yaml
2024-03-06 17:05:43,058 DEBUG   HandlerThread:71340 [meta.py:_save_conda():84] save conda done
2024-03-06 17:05:43,058 DEBUG   HandlerThread:71340 [meta.py:probe():247] probe done
2024-03-06 17:05:43,137 DEBUG   SenderThread:71340 [sender.py:send():235] send: files
2024-03-06 17:05:43,137 INFO    SenderThread:71340 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2024-03-06 17:05:43,138 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:05:43,139 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:05:43,143 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\conda-environment.yaml
2024-03-06 17:05:43,144 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170531-2igzsq6a\files\wandb-metadata.json
2024-03-06 17:05:43,145 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:05:44,452 DEBUG   SenderThread:71340 [sender.py:send():235] send: telemetry
2024-03-06 17:05:44,453 DEBUG   SenderThread:71340 [sender.py:send():235] send: metric
2024-03-06 17:05:44,455 DEBUG   SenderThread:71340 [sender.py:send():235] send: telemetry
2024-03-06 17:05:44,456 DEBUG   SenderThread:71340 [sender.py:send():235] send: metric
2024-03-06 17:05:44,457 WARNING SenderThread:71340 [sender.py:send_metric():905] Seen metric with glob (shouldn't happen)
2024-03-06 17:05:44,457 DEBUG   SenderThread:71340 [sender.py:send():235] send: config
2024-03-06 17:05:45,017 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:05:45,017 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:05:45,017 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:05:45,153 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:05:46,817 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:05:46,817 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:05:46,817 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:05:49,754 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:05:49,754 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:05:49,755 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:05:49,755 ERROR   Thread-22 :71340 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 17:05:54,738 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:05:54,738 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:05:54,738 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:05:59,285 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:05:59,467 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:05:59,467 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:06:01,302 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:06:04,512 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:06:04,513 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:06:04,513 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:06:07,355 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\config.yaml
2024-03-06 17:06:10,040 DEBUG   SenderThread:71340 [sender.py:send():235] send: stats
2024-03-06 17:06:15,812 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:06:15,813 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:06:21,238 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:06:21,238 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:06:21,238 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:06:32,134 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:06:32,135 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:06:43,133 DEBUG   SenderThread:71340 [sender.py:send():235] send: stats
2024-03-06 17:06:48,384 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:06:48,385 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:07:00,562 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:07:00,562 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:07:00,562 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:07:05,013 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:07:05,014 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:07:16,310 DEBUG   SenderThread:71340 [sender.py:send():235] send: stats
2024-03-06 17:07:21,323 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:07:21,323 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:07:37,557 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:07:37,557 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:07:49,433 DEBUG   SenderThread:71340 [sender.py:send():235] send: stats
2024-03-06 17:07:53,874 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:07:53,875 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:08:02,449 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:06,496 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:10,282 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:08:10,283 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:08:10,530 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:11,957 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2igzsq6a/wandb-metadata.json?Expires=1709802344&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nPi3MLUvukp9oX2iPYXzArkLSJkQSJWOfUa0CZ2HRhz0u2Xz%2BiUDtv2S3t6gRsguKhwNg5pMI%2BQt0fxy9KJjRkmI533frrCOd%2B92ls4yLt9YWITK4WUIB9b1dVdlDtYZO1rYTW3JQfJjav%2BrTYR%2FHMrBaqdM5jF1pl4tae7QuqAriIJQy9s8pqsi9WUBQIB%2FH%2FBpmeaKkUn%2B2nLwtlB7GqefuzZWdyPJZXWn7NKrY8eWPMVp%2F5J8ksO4vrDr4Q%2Fv0ryCujX7J%2Ft7E9DgsVmf3aguKSB5ZWXAyFX6EyODNNmk81zg9BO17kRaBBcwo5OQGUZh6IPI2AyqEFcQxWMGHQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 17:08:11,958 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 17:08:11,958 ERROR   Thread-22 :71340 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 17:08:12,543 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:14,558 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:18,575 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:22,509 DEBUG   SenderThread:71340 [sender.py:send():235] send: stats
2024-03-06 17:08:26,556 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 17:08:26,557 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: stop_status
2024-03-06 17:08:26,582 WARNING MainThread:71340 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-03-06 17:08:27,571 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:08:27,678 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\output.log
2024-03-06 17:08:27,814 DEBUG   SenderThread:71340 [sender.py:send():235] send: telemetry
2024-03-06 17:08:27,814 DEBUG   SenderThread:71340 [sender.py:send():235] send: exit
2024-03-06 17:08:27,814 INFO    SenderThread:71340 [sender.py:send_exit():371] handling exit code: 0
2024-03-06 17:08:27,815 INFO    SenderThread:71340 [sender.py:send_exit():373] handling runtime: 168
2024-03-06 17:08:27,815 INFO    SenderThread:71340 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:08:27,816 INFO    SenderThread:71340 [sender.py:send_exit():379] send defer
2024-03-06 17:08:27,816 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:08:27,816 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:08:27,817 INFO    HandlerThread:71340 [handler.py:handle_request_defer():164] handle defer: 0
2024-03-06 17:08:27,817 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: defer
2024-03-06 17:08:27,817 INFO    SenderThread:71340 [sender.py:send_request_defer():388] handle sender defer: 0
2024-03-06 17:08:27,817 INFO    SenderThread:71340 [sender.py:transition_state():392] send defer: 1
2024-03-06 17:08:27,817 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:08:27,817 INFO    HandlerThread:71340 [handler.py:handle_request_defer():164] handle defer: 1
2024-03-06 17:08:27,962 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:08:27,962 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: defer
2024-03-06 17:08:27,962 INFO    SenderThread:71340 [sender.py:send_request_defer():388] handle sender defer: 1
2024-03-06 17:08:27,963 INFO    SenderThread:71340 [sender.py:transition_state():392] send defer: 2
2024-03-06 17:08:27,963 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 17:08:27,963 DEBUG   SenderThread:71340 [sender.py:send():235] send: stats
2024-03-06 17:08:27,964 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:08:27,964 INFO    HandlerThread:71340 [handler.py:handle_request_defer():164] handle defer: 2
2024-03-06 17:08:27,964 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: defer
2024-03-06 17:08:27,964 INFO    SenderThread:71340 [sender.py:send_request_defer():388] handle sender defer: 2
2024-03-06 17:08:27,964 INFO    SenderThread:71340 [sender.py:transition_state():392] send defer: 3
2024-03-06 17:08:27,965 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:08:27,965 INFO    HandlerThread:71340 [handler.py:handle_request_defer():164] handle defer: 3
2024-03-06 17:08:27,965 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: defer
2024-03-06 17:08:27,965 INFO    SenderThread:71340 [sender.py:send_request_defer():388] handle sender defer: 3
2024-03-06 17:08:27,965 INFO    SenderThread:71340 [sender.py:transition_state():392] send defer: 4
2024-03-06 17:08:27,966 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:08:27,966 INFO    HandlerThread:71340 [handler.py:handle_request_defer():164] handle defer: 4
2024-03-06 17:08:27,966 DEBUG   SenderThread:71340 [sender.py:send():235] send: summary
2024-03-06 17:08:27,967 INFO    SenderThread:71340 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 17:08:27,967 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: defer
2024-03-06 17:08:27,967 INFO    SenderThread:71340 [sender.py:send_request_defer():388] handle sender defer: 4
2024-03-06 17:08:27,967 INFO    SenderThread:71340 [sender.py:transition_state():392] send defer: 5
2024-03-06 17:08:27,967 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: defer
2024-03-06 17:08:27,968 INFO    HandlerThread:71340 [handler.py:handle_request_defer():164] handle defer: 5
2024-03-06 17:08:27,968 DEBUG   SenderThread:71340 [sender.py:send_request():249] send_request: defer
2024-03-06 17:08:27,968 INFO    SenderThread:71340 [sender.py:send_request_defer():388] handle sender defer: 5
2024-03-06 17:08:28,074 DEBUG   HandlerThread:71340 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 17:08:28,689 INFO    Thread-16 :71340 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_170531-2igzsq6a\files\wandb-summary.json
