2024-03-06 15:08:20,570 INFO    MainThread:52808 [internal.py:wandb_internal():90] W&B internal server running at pid: 52808, started at: 2024-03-06 15:08:20.568631
2024-03-06 15:08:20,573 INFO    WriterThread:52808 [datastore.py:open_for_write():75] open: .\wandb\run-20240306_150818-2z2x4hn5\run-2z2x4hn5.wandb
2024-03-06 15:08:20,579 DEBUG   SenderThread:52808 [sender.py:send():235] send: header
2024-03-06 15:08:20,579 DEBUG   SenderThread:52808 [sender.py:send():235] send: run
2024-03-06 15:08:20,583 INFO    SenderThread:52808 [sender.py:_maybe_setup_resume():492] checking resume status for None/UNet-DAS/2z2x4hn5
2024-03-06 15:08:23,474 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: check_version
2024-03-06 15:08:23,511 INFO    SenderThread:52808 [dir_watcher.py:__init__():205] watching files in: .\wandb\run-20240306_150818-2z2x4hn5\files
2024-03-06 15:08:23,511 INFO    SenderThread:52808 [sender.py:_start_run_threads():812] run started: 2z2x4hn5 with start time 1709708899
2024-03-06 15:08:23,511 DEBUG   SenderThread:52808 [sender.py:send():235] send: summary
2024-03-06 15:08:23,512 INFO    SenderThread:52808 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:08:23,513 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: check_version
2024-03-06 15:08:24,483 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: run_start
2024-03-06 15:08:24,509 DEBUG   HandlerThread:52808 [meta.py:__init__():35] meta init
2024-03-06 15:08:24,509 DEBUG   HandlerThread:52808 [meta.py:__init__():49] meta init done
2024-03-06 15:08:24,510 DEBUG   HandlerThread:52808 [meta.py:probe():209] probe
2024-03-06 15:08:24,520 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_150818-2z2x4hn5\files\wandb-summary.json
2024-03-06 15:08:24,533 DEBUG   HandlerThread:52808 [meta.py:_setup_git():199] setup git
2024-03-06 15:08:24,699 DEBUG   HandlerThread:52808 [meta.py:_setup_git():206] setup git done
2024-03-06 15:08:24,699 DEBUG   HandlerThread:52808 [meta.py:_save_pip():53] save pip
2024-03-06 15:08:24,701 DEBUG   HandlerThread:52808 [meta.py:_save_pip():67] save pip done
2024-03-06 15:08:24,701 DEBUG   HandlerThread:52808 [meta.py:_save_conda():74] save conda
2024-03-06 15:08:25,531 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_150818-2z2x4hn5\files\requirements.txt
2024-03-06 15:08:25,531 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_150818-2z2x4hn5\files\conda-environment.yaml
2024-03-06 15:08:28,827 DEBUG   HandlerThread:52808 [meta.py:_save_conda():84] save conda done
2024-03-06 15:08:28,827 DEBUG   HandlerThread:52808 [meta.py:probe():247] probe done
2024-03-06 15:08:28,840 DEBUG   SenderThread:52808 [sender.py:send():235] send: files
2024-03-06 15:08:28,840 INFO    SenderThread:52808 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2024-03-06 15:08:28,852 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:08:28,852 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:08:29,549 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\conda-environment.yaml
2024-03-06 15:08:29,550 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_150818-2z2x4hn5\files\wandb-metadata.json
2024-03-06 15:08:29,550 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_150818-2z2x4hn5\files\output.log
2024-03-06 15:08:30,209 DEBUG   SenderThread:52808 [sender.py:send():235] send: telemetry
2024-03-06 15:08:30,209 DEBUG   SenderThread:52808 [sender.py:send():235] send: metric
2024-03-06 15:08:30,209 DEBUG   SenderThread:52808 [sender.py:send():235] send: telemetry
2024-03-06 15:08:30,209 DEBUG   SenderThread:52808 [sender.py:send():235] send: metric
2024-03-06 15:08:30,209 WARNING SenderThread:52808 [sender.py:send_metric():905] Seen metric with glob (shouldn't happen)
2024-03-06 15:08:30,209 DEBUG   SenderThread:52808 [sender.py:send():235] send: config
2024-03-06 15:08:30,853 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:08:30,854 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:08:30,854 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:08:31,564 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\output.log
2024-03-06 15:08:32,480 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:08:32,480 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:08:32,481 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:08:35,360 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:08:35,361 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:08:35,361 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:08:35,361 ERROR   Thread-22 :52808 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 15:08:40,964 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:08:40,965 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:08:40,965 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:08:45,224 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:08:45,225 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:08:45,671 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\output.log
2024-03-06 15:08:50,591 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:08:50,592 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:08:50,592 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:08:53,742 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\config.yaml
2024-03-06 15:08:55,656 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:09:02,078 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:09:02,078 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:09:08,003 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:09:08,003 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:09:08,003 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:09:22,063 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:09:22,063 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:09:28,894 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:09:38,684 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:09:38,684 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:09:43,595 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:09:43,595 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:09:43,595 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:09:58,700 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:09:58,701 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:10:02,127 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:10:14,985 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:10:14,985 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:10:35,004 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:10:35,005 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:10:36,545 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:10:51,549 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:10:51,550 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:10:59,314 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-metadata.json?Expires=1709795310&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=GxyTxPIKdi%2B7Q2xZzfTFEFlq5PJIhu9zA7%2Fhv9rTPblwEYcNvzBGFT%2BHo%2FnTSfW7vOU3%2FSM1bj67DkSv54%2FN0LBQDw8Efq4DDt10B6tEF78vYSGTreb4BLYgGlKYdL7efcikIH%2BO0ADq2MsredZgbDgxyqYpiiLpGMb%2Bbf1XXzaEysec9E1bOv04K81ehlismig%2FOb32obcuISw%2Bf2FgekmAlfC%2FXhucj%2FLPHcgnCWyVOI4lxuxZ6QuS%2F8J0h5FPjShqCvBsdDP5KTTxAZe5ps5Fwf9u3FQDtpzUZ5hdwflCRFeXvgoHJS73FNYCHsT%2BbBA06aWrfjq53GDtaGOBig%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:10:59,314 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:10:59,314 ERROR   Thread-22 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:11:07,951 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:11:07,952 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:11:09,327 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:11:24,331 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:11:24,332 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:11:40,764 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:11:40,764 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:11:43,302 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:11:58,306 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:11:58,307 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:12:14,767 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:12:14,768 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:12:16,393 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:12:31,401 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:12:31,402 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:12:38,931 WARNING MainThread:52808 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-03-06 15:12:39,912 DEBUG   SenderThread:52808 [sender.py:send():235] send: telemetry
2024-03-06 15:12:39,922 DEBUG   SenderThread:52808 [sender.py:send():235] send: exit
2024-03-06 15:12:39,923 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:39,923 INFO    SenderThread:52808 [sender.py:send_exit():371] handling exit code: 0
2024-03-06 15:12:39,923 INFO    SenderThread:52808 [sender.py:send_exit():373] handling runtime: 255
2024-03-06 15:12:39,924 INFO    SenderThread:52808 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:12:39,925 INFO    SenderThread:52808 [sender.py:send_exit():379] send defer
2024-03-06 15:12:39,925 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:39,926 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:39,926 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 0
2024-03-06 15:12:39,926 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:39,926 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 0
2024-03-06 15:12:39,926 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 1
2024-03-06 15:12:39,926 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:39,926 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 1
2024-03-06 15:12:40,031 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:40,031 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:40,031 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 1
2024-03-06 15:12:40,031 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 2
2024-03-06 15:12:40,031 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:40,032 DEBUG   SenderThread:52808 [sender.py:send():235] send: stats
2024-03-06 15:12:40,032 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:40,032 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 2
2024-03-06 15:12:40,033 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:40,033 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 2
2024-03-06 15:12:40,033 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 3
2024-03-06 15:12:40,033 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:40,033 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 3
2024-03-06 15:12:40,033 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:40,033 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 3
2024-03-06 15:12:40,034 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 4
2024-03-06 15:12:40,034 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:40,034 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 4
2024-03-06 15:12:40,034 DEBUG   SenderThread:52808 [sender.py:send():235] send: summary
2024-03-06 15:12:40,035 INFO    SenderThread:52808 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:12:40,035 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:40,036 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 4
2024-03-06 15:12:40,036 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 5
2024-03-06 15:12:40,036 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:40,036 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 5
2024-03-06 15:12:40,036 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:40,036 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 5
2024-03-06 15:12:40,135 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:40,519 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\wandb-summary.json
2024-03-06 15:12:40,520 INFO    Thread-16 :52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\output.log
2024-03-06 15:12:41,459 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 6
2024-03-06 15:12:41,459 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:41,459 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:41,460 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 6
2024-03-06 15:12:41,460 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:41,460 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 6
2024-03-06 15:12:41,460 INFO    SenderThread:52808 [dir_watcher.py:finish():336] shutting down directory watcher
2024-03-06 15:12:41,529 INFO    SenderThread:52808 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_150818-2z2x4hn5\files\config.yaml
2024-03-06 15:12:41,529 INFO    SenderThread:52808 [dir_watcher.py:finish():366] scan: .\wandb\run-20240306_150818-2z2x4hn5\files
2024-03-06 15:12:41,529 INFO    SenderThread:52808 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_150818-2z2x4hn5\files\conda-environment.yaml conda-environment.yaml
2024-03-06 15:12:41,530 INFO    SenderThread:52808 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_150818-2z2x4hn5\files\config.yaml config.yaml
2024-03-06 15:12:41,536 INFO    SenderThread:52808 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_150818-2z2x4hn5\files\output.log output.log
2024-03-06 15:12:41,546 INFO    SenderThread:52808 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_150818-2z2x4hn5\files\requirements.txt requirements.txt
2024-03-06 15:12:41,553 INFO    SenderThread:52808 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_150818-2z2x4hn5\files\wandb-metadata.json wandb-metadata.json
2024-03-06 15:12:41,554 INFO    SenderThread:52808 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_150818-2z2x4hn5\files\wandb-summary.json wandb-summary.json
2024-03-06 15:12:41,562 INFO    SenderThread:52808 [sender.py:transition_state():392] send defer: 7
2024-03-06 15:12:41,563 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:12:41,568 INFO    HandlerThread:52808 [handler.py:handle_request_defer():164] handle defer: 7
2024-03-06 15:12:41,569 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: defer
2024-03-06 15:12:41,570 INFO    SenderThread:52808 [sender.py:send_request_defer():388] handle sender defer: 7
2024-03-06 15:12:41,570 INFO    SenderThread:52808 [file_pusher.py:finish():145] shutting down file pusher
2024-03-06 15:12:41,573 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:41,573 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:41,680 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:41,681 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:41,790 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:41,791 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:41,898 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:41,899 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,006 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,007 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,113 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,113 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,221 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,222 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,328 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,329 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,437 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,438 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,546 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,547 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,654 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,655 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,763 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,763 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,869 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,870 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:42,977 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:42,978 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,085 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,086 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,194 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,195 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,304 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,305 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,413 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,414 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,519 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,520 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,622 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/conda-environment.yaml?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=thDkGx7ruGneP%2BO7Zo9p%2F14hLteqj2kRsTVaw15s%2FSCDc3blYdhcKJ%2BGaOe7tzb0ERy6JFBpwH%2FK50PqJittnvbFabXFyA0yZblbGEUnrtppXnkE5kHd8F8AWjbqKhykrFuEyKrkhDjPR8b7qH27QFZt8b%2FeCl1pjwSgkV72EPm1pKDzWIxh6vOX2qA%2B2A%2B%2BxuCJKUhgf%2FXD4y%2FKfhC6wcHqmmXk9y2XmbKKhMmRWJxf71HmHRbqWA8%2BBSTZMTygMyS5r0WWXGk7R4Zz3pwWclaQvvSvc1rbAnMUhH6aqryWxLl1UdwrlcjdmPjkhEkkOGJPp%2F7nuixkYiPrE6wlWw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:43,623 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1983'}
2024-03-06 15:12:43,623 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:43,630 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,630 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,736 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,736 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,745 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/output.log?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uAfIGy9L3BsaWpUiugWcgltmDeRqDwFEb4ls87bCOaVjb0yjZJOJMTgc9akzmL7jRK4PSHSWDYHRbHicj%2BJRbD7Yqcl%2Bm8wVOO%2BEsccF1lzal4OoQ75gM7jxnjc97cgwQy%2F%2F9zD6OREdqpemDAo%2F1y7581L6pmQdSVH8jCpDO1AcygwNz%2BXUiPXpD2c4fdauXxxEHY4UYPIVIZQ9FAB0Du2XPiW2MOm1XCJ6nWfYMh8ICGRnYgduYrC%2BEOaiojCG78sF3fQ72TMyr7KMXCCrMjWDNgb7%2FdKNUu%2B6gee53RRaAn1CU8kbEppUNC0JAmGDeOiBFVTqD7He9D4huUUvbw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:43,745 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '242'}
2024-03-06 15:12:43,745 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:43,786 ERROR   Thread-24 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/config.yaml?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=nHk7hg4eX4GkVQh0cyN40JViC0ZYLV96yIc5TQ5lyE8ioFEoQJsy%2BtGFHolUFkuHGQEpYr7ows9zuzeHT6i2QIY%2B%2BQfmm3%2FGM05wjq9c7W%2BISDZ5zLGix6YogJDCcAP%2F8FOTygTSkIEvxTJrWMJOXoq0vcIumyQe0l1wOv4018T3eZa4ocG7KgzLVbZ8IKWt16O2HDsZHYPho3pfd%2FFA7tMqH4gT8%2Fbufqjsosi4sFBGmZ2yLJakVbynPaeE1CxwTgyoZTXpGI8MImCSPLz%2FIkiyU22AnwnKaIdx3XUXCFgKUdJowYYpOjP6k9552YgnaBNfzyqI5Xr7nXzG1si%2FEQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:43,786 ERROR   Thread-24 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1577'}
2024-03-06 15:12:43,786 ERROR   Thread-24 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:43,844 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,845 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,955 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:43,956 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:43,959 ERROR   Thread-26 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/requirements.txt?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=dwl3W4O%2BKOaQbU2wmITkZiOaBFl97cIB5DDNDhxXcVdH9m8PQvxMsPXKdKQKxATttodEDoatRRTJmakI2vllwiIetT65IHjDTJWLSUackTGQJw1yHup%2BhWLjLyZ97kOGxEVXtMKdIsY20UbsyoQS1v9Hdzg3X5YK3IrHMcKjXKteS5XdoHjEwQORaG8RFpDF7QY%2BkfyPG%2F6XxC0SxTdtxeXGv7h7cJw%2FEkZcPeg1C7IpsLFeVus7c6kGyjdMApOX4wSeSb0ZLpNXfUpUNdI8CGjxmKsBeqEM52QQd%2Fr7xOr8XEJhA1cmWLaDPBsaBjJccRX03UXbrTP7KHVrNXcu9A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:43,959 ERROR   Thread-26 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1252'}
2024-03-06 15:12:43,959 ERROR   Thread-26 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:44,061 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,062 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,171 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,171 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,278 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,279 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,387 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,388 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,492 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,493 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,600 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,601 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,708 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,709 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,814 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,814 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:44,921 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:44,922 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,026 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,027 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,132 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,133 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,239 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,240 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,347 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,347 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,439 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/conda-environment.yaml?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=thDkGx7ruGneP%2BO7Zo9p%2F14hLteqj2kRsTVaw15s%2FSCDc3blYdhcKJ%2BGaOe7tzb0ERy6JFBpwH%2FK50PqJittnvbFabXFyA0yZblbGEUnrtppXnkE5kHd8F8AWjbqKhykrFuEyKrkhDjPR8b7qH27QFZt8b%2FeCl1pjwSgkV72EPm1pKDzWIxh6vOX2qA%2B2A%2B%2BxuCJKUhgf%2FXD4y%2FKfhC6wcHqmmXk9y2XmbKKhMmRWJxf71HmHRbqWA8%2BBSTZMTygMyS5r0WWXGk7R4Zz3pwWclaQvvSvc1rbAnMUhH6aqryWxLl1UdwrlcjdmPjkhEkkOGJPp%2F7nuixkYiPrE6wlWw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:45,439 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1983'}
2024-03-06 15:12:45,439 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:45,454 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,454 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,563 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,564 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,603 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/output.log?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uAfIGy9L3BsaWpUiugWcgltmDeRqDwFEb4ls87bCOaVjb0yjZJOJMTgc9akzmL7jRK4PSHSWDYHRbHicj%2BJRbD7Yqcl%2Bm8wVOO%2BEsccF1lzal4OoQ75gM7jxnjc97cgwQy%2F%2F9zD6OREdqpemDAo%2F1y7581L6pmQdSVH8jCpDO1AcygwNz%2BXUiPXpD2c4fdauXxxEHY4UYPIVIZQ9FAB0Du2XPiW2MOm1XCJ6nWfYMh8ICGRnYgduYrC%2BEOaiojCG78sF3fQ72TMyr7KMXCCrMjWDNgb7%2FdKNUu%2B6gee53RRaAn1CU8kbEppUNC0JAmGDeOiBFVTqD7He9D4huUUvbw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:45,603 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '242'}
2024-03-06 15:12:45,603 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:45,670 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,671 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,776 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,777 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,885 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,886 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:45,992 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:45,993 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,100 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,101 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,208 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,209 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,260 INFO    Thread-24 :52808 [upload_job.py:push():132] Uploaded file .\wandb\run-20240306_150818-2z2x4hn5\files\config.yaml
2024-03-06 15:12:46,313 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,314 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,362 INFO    Thread-26 :52808 [upload_job.py:push():132] Uploaded file .\wandb\run-20240306_150818-2z2x4hn5\files\requirements.txt
2024-03-06 15:12:46,423 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,424 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,531 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,531 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,638 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,639 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,746 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,747 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,852 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,853 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:46,960 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:46,961 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,067 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,067 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,176 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,177 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,284 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,285 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,393 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,394 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,501 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,502 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,608 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,609 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,714 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,715 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,820 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,821 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:47,927 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:47,928 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,033 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,033 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,142 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,143 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,252 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,253 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,339 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-summary.json?Expires=1709795568&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VEHL7PaN9w1JUisjj%2BfgAEMNX%2B5nZ84T0UhiswfPCTaVKoLJ6QCpDaJrxOXMFGGgMHr8FLKu8VbDQaIkz3NXwUK3f0%2BgwnthWTrn20cGyGhwBlr%2BgiL0ST84Ok7reZ%2BwUFqef3K8X%2FI4M1ZuvQme5MbVjb6W%2Ba33bzrVM2judkj1vKqIBJxSu9pUjkD7C5GTg4q71DWZMlwUUM%2FEg%2BYGpSkZk3vTMSDpmCcY26LvfiKaOSeQ34xWnceLruEP7XEiy4AhsST6nuNd1k8PlhVvQ2TTFdtb5fGpWUp5%2B982xAJxrwMpPRcnQ5WcHOVTz3dgr%2F6cyfCvRgS%2Fk6boW0J10A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:48,340 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2024-03-06 15:12:48,340 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:48,359 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,360 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,470 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,471 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,578 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,579 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,619 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/conda-environment.yaml?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=thDkGx7ruGneP%2BO7Zo9p%2F14hLteqj2kRsTVaw15s%2FSCDc3blYdhcKJ%2BGaOe7tzb0ERy6JFBpwH%2FK50PqJittnvbFabXFyA0yZblbGEUnrtppXnkE5kHd8F8AWjbqKhykrFuEyKrkhDjPR8b7qH27QFZt8b%2FeCl1pjwSgkV72EPm1pKDzWIxh6vOX2qA%2B2A%2B%2BxuCJKUhgf%2FXD4y%2FKfhC6wcHqmmXk9y2XmbKKhMmRWJxf71HmHRbqWA8%2BBSTZMTygMyS5r0WWXGk7R4Zz3pwWclaQvvSvc1rbAnMUhH6aqryWxLl1UdwrlcjdmPjkhEkkOGJPp%2F7nuixkYiPrE6wlWw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:48,620 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1983'}
2024-03-06 15:12:48,620 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:48,689 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,690 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,692 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/output.log?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uAfIGy9L3BsaWpUiugWcgltmDeRqDwFEb4ls87bCOaVjb0yjZJOJMTgc9akzmL7jRK4PSHSWDYHRbHicj%2BJRbD7Yqcl%2Bm8wVOO%2BEsccF1lzal4OoQ75gM7jxnjc97cgwQy%2F%2F9zD6OREdqpemDAo%2F1y7581L6pmQdSVH8jCpDO1AcygwNz%2BXUiPXpD2c4fdauXxxEHY4UYPIVIZQ9FAB0Du2XPiW2MOm1XCJ6nWfYMh8ICGRnYgduYrC%2BEOaiojCG78sF3fQ72TMyr7KMXCCrMjWDNgb7%2FdKNUu%2B6gee53RRaAn1CU8kbEppUNC0JAmGDeOiBFVTqD7He9D4huUUvbw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:48,692 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '242'}
2024-03-06 15:12:48,692 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:48,798 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,799 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:48,905 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:48,905 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,011 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,012 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,119 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,120 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,227 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,228 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,336 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,337 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,446 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,447 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,553 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,554 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,658 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,659 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,765 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,766 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,871 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,872 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:49,979 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:49,980 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,070 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-summary.json?Expires=1709795568&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VEHL7PaN9w1JUisjj%2BfgAEMNX%2B5nZ84T0UhiswfPCTaVKoLJ6QCpDaJrxOXMFGGgMHr8FLKu8VbDQaIkz3NXwUK3f0%2BgwnthWTrn20cGyGhwBlr%2BgiL0ST84Ok7reZ%2BwUFqef3K8X%2FI4M1ZuvQme5MbVjb6W%2Ba33bzrVM2judkj1vKqIBJxSu9pUjkD7C5GTg4q71DWZMlwUUM%2FEg%2BYGpSkZk3vTMSDpmCcY26LvfiKaOSeQ34xWnceLruEP7XEiy4AhsST6nuNd1k8PlhVvQ2TTFdtb5fGpWUp5%2B982xAJxrwMpPRcnQ5WcHOVTz3dgr%2F6cyfCvRgS%2Fk6boW0J10A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:50,071 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2024-03-06 15:12:50,071 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:50,071 ERROR   Thread-27 :52808 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 15:12:50,085 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,086 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,191 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,191 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,299 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,300 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,407 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,408 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,517 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,518 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,625 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,626 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,733 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,734 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,842 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,843 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:50,950 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:50,951 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,056 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,057 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,164 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,165 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,272 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,273 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,382 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,382 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,488 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,489 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,598 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,599 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,706 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,707 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,813 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,814 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:51,920 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:51,921 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,031 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,031 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,140 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,141 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,247 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,248 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,355 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,356 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,463 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,464 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,570 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,571 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,679 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,680 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,788 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,789 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:52,896 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:52,896 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,003 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,004 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,110 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,111 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,166 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/wandb-summary.json?Expires=1709795568&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=VEHL7PaN9w1JUisjj%2BfgAEMNX%2B5nZ84T0UhiswfPCTaVKoLJ6QCpDaJrxOXMFGGgMHr8FLKu8VbDQaIkz3NXwUK3f0%2BgwnthWTrn20cGyGhwBlr%2BgiL0ST84Ok7reZ%2BwUFqef3K8X%2FI4M1ZuvQme5MbVjb6W%2Ba33bzrVM2judkj1vKqIBJxSu9pUjkD7C5GTg4q71DWZMlwUUM%2FEg%2BYGpSkZk3vTMSDpmCcY26LvfiKaOSeQ34xWnceLruEP7XEiy4AhsST6nuNd1k8PlhVvQ2TTFdtb5fGpWUp5%2B982xAJxrwMpPRcnQ5WcHOVTz3dgr%2F6cyfCvRgS%2Fk6boW0J10A%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:53,166 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '28'}
2024-03-06 15:12:53,166 ERROR   Thread-27 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:53,216 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,217 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,325 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,326 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,416 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/output.log?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=uAfIGy9L3BsaWpUiugWcgltmDeRqDwFEb4ls87bCOaVjb0yjZJOJMTgc9akzmL7jRK4PSHSWDYHRbHicj%2BJRbD7Yqcl%2Bm8wVOO%2BEsccF1lzal4OoQ75gM7jxnjc97cgwQy%2F%2F9zD6OREdqpemDAo%2F1y7581L6pmQdSVH8jCpDO1AcygwNz%2BXUiPXpD2c4fdauXxxEHY4UYPIVIZQ9FAB0Du2XPiW2MOm1XCJ6nWfYMh8ICGRnYgduYrC%2BEOaiojCG78sF3fQ72TMyr7KMXCCrMjWDNgb7%2FdKNUu%2B6gee53RRaAn1CU8kbEppUNC0JAmGDeOiBFVTqD7He9D4huUUvbw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:53,416 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '242'}
2024-03-06 15:12:53,416 ERROR   Thread-25 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:53,433 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,434 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,542 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,543 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,651 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,652 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,759 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,760 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,866 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,866 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:53,975 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:53,976 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:54,086 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:54,087 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:54,193 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:54,194 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:54,197 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2z2x4hn5/conda-environment.yaml?Expires=1709795563&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=thDkGx7ruGneP%2BO7Zo9p%2F14hLteqj2kRsTVaw15s%2FSCDc3blYdhcKJ%2BGaOe7tzb0ERy6JFBpwH%2FK50PqJittnvbFabXFyA0yZblbGEUnrtppXnkE5kHd8F8AWjbqKhykrFuEyKrkhDjPR8b7qH27QFZt8b%2FeCl1pjwSgkV72EPm1pKDzWIxh6vOX2qA%2B2A%2B%2BxuCJKUhgf%2FXD4y%2FKfhC6wcHqmmXk9y2XmbKKhMmRWJxf71HmHRbqWA8%2BBSTZMTygMyS5r0WWXGk7R4Zz3pwWclaQvvSvc1rbAnMUhH6aqryWxLl1UdwrlcjdmPjkhEkkOGJPp%2F7nuixkYiPrE6wlWw%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:12:54,197 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '1983'}
2024-03-06 15:12:54,197 ERROR   Thread-23 :52808 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:12:54,300 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:54,301 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:12:54,408 DEBUG   HandlerThread:52808 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:12:54,408 DEBUG   SenderThread:52808 [sender.py:send_request():249] send_request: poll_exit
