2024-03-06 15:13:11,844 INFO    MainThread:47720 [internal.py:wandb_internal():90] W&B internal server running at pid: 47720, started at: 2024-03-06 15:13:11.844276
2024-03-06 15:13:11,847 INFO    WriterThread:47720 [datastore.py:open_for_write():75] open: .\wandb\run-20240306_151309-2p64vwh8\run-2p64vwh8.wandb
2024-03-06 15:13:11,854 DEBUG   SenderThread:47720 [sender.py:send():235] send: header
2024-03-06 15:13:11,854 DEBUG   SenderThread:47720 [sender.py:send():235] send: run
2024-03-06 15:13:11,858 INFO    SenderThread:47720 [sender.py:_maybe_setup_resume():492] checking resume status for None/UNet-DAS/2p64vwh8
2024-03-06 15:13:14,794 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: check_version
2024-03-06 15:13:14,832 INFO    SenderThread:47720 [dir_watcher.py:__init__():205] watching files in: .\wandb\run-20240306_151309-2p64vwh8\files
2024-03-06 15:13:14,832 INFO    SenderThread:47720 [sender.py:_start_run_threads():812] run started: 2p64vwh8 with start time 1709709190
2024-03-06 15:13:14,832 DEBUG   SenderThread:47720 [sender.py:send():235] send: summary
2024-03-06 15:13:14,833 INFO    SenderThread:47720 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:13:14,834 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: check_version
2024-03-06 15:13:15,843 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_151309-2p64vwh8\files\wandb-summary.json
2024-03-06 15:13:15,890 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: run_start
2024-03-06 15:13:15,917 DEBUG   HandlerThread:47720 [meta.py:__init__():35] meta init
2024-03-06 15:13:15,917 DEBUG   HandlerThread:47720 [meta.py:__init__():49] meta init done
2024-03-06 15:13:15,917 DEBUG   HandlerThread:47720 [meta.py:probe():209] probe
2024-03-06 15:13:15,965 DEBUG   HandlerThread:47720 [meta.py:_setup_git():199] setup git
2024-03-06 15:13:16,110 DEBUG   HandlerThread:47720 [meta.py:_setup_git():206] setup git done
2024-03-06 15:13:16,111 DEBUG   HandlerThread:47720 [meta.py:_save_pip():53] save pip
2024-03-06 15:13:16,112 DEBUG   HandlerThread:47720 [meta.py:_save_pip():67] save pip done
2024-03-06 15:13:16,112 DEBUG   HandlerThread:47720 [meta.py:_save_conda():74] save conda
2024-03-06 15:13:16,846 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_151309-2p64vwh8\files\conda-environment.yaml
2024-03-06 15:13:16,847 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_151309-2p64vwh8\files\requirements.txt
2024-03-06 15:13:19,854 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\conda-environment.yaml
2024-03-06 15:13:19,911 DEBUG   HandlerThread:47720 [meta.py:_save_conda():84] save conda done
2024-03-06 15:13:19,911 DEBUG   HandlerThread:47720 [meta.py:probe():247] probe done
2024-03-06 15:13:19,985 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:13:19,985 DEBUG   SenderThread:47720 [sender.py:send():235] send: files
2024-03-06 15:13:19,986 INFO    SenderThread:47720 [sender.py:_save_file():949] saving file wandb-metadata.json with policy now
2024-03-06 15:13:19,987 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:13:20,859 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\conda-environment.yaml
2024-03-06 15:13:20,860 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_151309-2p64vwh8\files\wandb-metadata.json
2024-03-06 15:13:20,860 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_created():256] file/dir created: .\wandb\run-20240306_151309-2p64vwh8\files\output.log
2024-03-06 15:13:22,111 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:13:22,111 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:13:22,112 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:13:22,868 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\output.log
2024-03-06 15:13:23,894 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:13:23,894 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:13:23,894 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:13:26,829 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:13:26,829 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:13:26,829 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:13:26,830 ERROR   Thread-22 :47720 [retry.py:__call__():126] Retry attempt failed:
Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [WinError 10054] 远程主机强迫关闭了一个现有的连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 486, in send
    resp = conn.urlopen(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 847, in urlopen
    retries = retries.increment(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\util.py", line 38, in reraise
    raise value.with_traceback(tb)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 793, in urlopen
    response = self._make_request(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 491, in _make_request
    raise new_e
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 467, in _make_request
    self._validate_conn(conn)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connectionpool.py", line 1099, in _validate_conn
    conn.connect()
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 653, in connect
    sock_and_verified = _ssl_wrap_socket_and_match_hostname(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\connection.py", line 806, in _ssl_wrap_socket_and_match_hostname
    ssl_sock = ssl_wrap_socket(
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 465, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(sock, context, tls_in_tls, server_hostname)
  File "E:\Anaconda\envs\unet\lib\site-packages\urllib3\util\ssl_.py", line 509, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1073, in _create
    self.do_handshake()
  File "E:\Anaconda\envs\unet\lib\ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\lib\retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1653, in upload_file
    raise e.with_traceback(sys.exc_info()[2])
  File "C:\Users\19086\AppData\Roaming\Python\Python38\site-packages\wandb\sdk\internal\internal_api.py", line 1637, in upload_file
    response = requests.put(url, data=progress, headers=extra_headers)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 130, in put
    return request("put", url, data=data, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "E:\Anaconda\envs\unet\lib\site-packages\requests\adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2024-03-06 15:13:32,404 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:13:32,404 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:13:32,404 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:13:33,380 DEBUG   SenderThread:47720 [sender.py:send():235] send: telemetry
2024-03-06 15:13:33,380 DEBUG   SenderThread:47720 [sender.py:send():235] send: metric
2024-03-06 15:13:33,380 DEBUG   SenderThread:47720 [sender.py:send():235] send: telemetry
2024-03-06 15:13:33,380 DEBUG   SenderThread:47720 [sender.py:send():235] send: metric
2024-03-06 15:13:33,380 WARNING SenderThread:47720 [sender.py:send_metric():905] Seen metric with glob (shouldn't happen)
2024-03-06 15:13:33,380 DEBUG   SenderThread:47720 [sender.py:send():235] send: config
2024-03-06 15:13:36,970 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\output.log
2024-03-06 15:13:39,946 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:13:39,946 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:13:42,499 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:13:42,499 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:13:42,499 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:13:44,020 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\config.yaml
2024-03-06 15:13:47,082 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:13:56,418 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:13:56,419 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:14:02,557 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:14:02,557 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:14:02,557 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:14:12,932 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:14:12,933 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:14:20,231 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:14:29,440 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:14:29,441 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:14:42,728 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:14:42,728 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:14:42,728 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:14:45,968 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:14:45,969 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:14:53,487 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:15:02,408 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:15:02,409 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:15:18,686 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:15:18,686 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:15:26,693 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:15:35,427 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:15:35,428 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:15:51,751 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:15:51,752 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:15:58,392 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1640] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/shahwaiz/UNet-DAS/2p64vwh8/wandb-metadata.json?Expires=1709795601&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=pGBZKrE%2F%2FPHSN4B7Taj0akxbkP9SRtS2qneGqwatdYIXA5JfjT5PLS89nALKvZTM0UVDHPJUyXlfbhSaMI4XRdmnO6n1Ljy%2FNC0PU10xWno0pqcn9ZINQhFELX2K2s%2F9rKHMQ%2F0WT9bVfRoCr%2FBSqLpteFwV4t5nNJsvu5xYWDtjI2rftO0HIQWvpq9J0%2B9j4cfeshU%2Bb%2Fj7CGZs5bWK13DjemQk2ESJ1LZKCOuyswzTMtxFjSSu4PAV6jvG1JpPO5YFN%2FMPTcaK0yBssMUPds3Q00cCA2SwbMVxRMwDty3PDxx%2BKXhBnEQlqY5S3cz38OOoiHme%2BxLr4sD9Pl8OiQ%3D%3D: ('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
2024-03-06 15:15:58,392 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1642] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '766'}
2024-03-06 15:15:58,393 ERROR   Thread-22 :47720 [internal_api.py:upload_file():1644] upload_file response body: 
2024-03-06 15:15:59,931 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:16:08,958 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:16:08,959 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:16:27,389 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:16:27,390 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:16:33,259 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:16:44,036 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:16:44,037 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:17:04,052 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:17:04,053 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:17:06,474 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:17:20,772 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:17:20,773 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:17:39,758 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:17:40,794 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: stop_status
2024-03-06 15:17:40,795 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: stop_status
2024-03-06 15:17:52,738 WARNING MainThread:47720 [internal.py:wandb_internal():153] Internal process interrupt: 1
2024-03-06 15:17:53,545 DEBUG   SenderThread:47720 [sender.py:send():235] send: telemetry
2024-03-06 15:17:54,035 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\output.log
2024-03-06 15:17:54,514 DEBUG   SenderThread:47720 [sender.py:send():235] send: exit
2024-03-06 15:17:54,515 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:54,515 INFO    SenderThread:47720 [sender.py:send_exit():371] handling exit code: 0
2024-03-06 15:17:54,515 INFO    SenderThread:47720 [sender.py:send_exit():373] handling runtime: 278
2024-03-06 15:17:54,516 INFO    SenderThread:47720 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:17:54,516 INFO    SenderThread:47720 [sender.py:send_exit():379] send defer
2024-03-06 15:17:54,516 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:54,517 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:54,517 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 0
2024-03-06 15:17:54,517 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:54,517 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 0
2024-03-06 15:17:54,517 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 1
2024-03-06 15:17:54,518 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:54,518 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 1
2024-03-06 15:17:54,666 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:54,666 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 1
2024-03-06 15:17:54,666 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:54,666 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 2
2024-03-06 15:17:54,667 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:54,667 DEBUG   SenderThread:47720 [sender.py:send():235] send: stats
2024-03-06 15:17:54,668 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:54,668 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 2
2024-03-06 15:17:54,668 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:54,668 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 2
2024-03-06 15:17:54,668 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 3
2024-03-06 15:17:54,669 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:54,669 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 3
2024-03-06 15:17:54,669 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:54,669 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 3
2024-03-06 15:17:54,669 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 4
2024-03-06 15:17:54,669 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:54,669 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 4
2024-03-06 15:17:54,670 DEBUG   SenderThread:47720 [sender.py:send():235] send: summary
2024-03-06 15:17:54,670 INFO    SenderThread:47720 [sender.py:_save_file():949] saving file wandb-summary.json with policy end
2024-03-06 15:17:54,671 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:54,671 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 4
2024-03-06 15:17:54,671 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 5
2024-03-06 15:17:54,671 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:54,671 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 5
2024-03-06 15:17:54,672 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:54,672 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 5
2024-03-06 15:17:54,770 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:55,037 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\wandb-summary.json
2024-03-06 15:17:55,038 INFO    Thread-16 :47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\output.log
2024-03-06 15:17:55,993 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 6
2024-03-06 15:17:55,993 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:55,994 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:55,994 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 6
2024-03-06 15:17:55,995 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:55,995 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 6
2024-03-06 15:17:55,995 INFO    SenderThread:47720 [dir_watcher.py:finish():336] shutting down directory watcher
2024-03-06 15:17:56,052 INFO    SenderThread:47720 [dir_watcher.py:_on_file_modified():269] file/dir modified: .\wandb\run-20240306_151309-2p64vwh8\files\config.yaml
2024-03-06 15:17:56,053 INFO    SenderThread:47720 [dir_watcher.py:finish():366] scan: .\wandb\run-20240306_151309-2p64vwh8\files
2024-03-06 15:17:56,053 INFO    SenderThread:47720 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_151309-2p64vwh8\files\conda-environment.yaml conda-environment.yaml
2024-03-06 15:17:56,054 INFO    SenderThread:47720 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_151309-2p64vwh8\files\config.yaml config.yaml
2024-03-06 15:17:56,060 INFO    SenderThread:47720 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_151309-2p64vwh8\files\output.log output.log
2024-03-06 15:17:56,070 INFO    SenderThread:47720 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_151309-2p64vwh8\files\requirements.txt requirements.txt
2024-03-06 15:17:56,077 INFO    SenderThread:47720 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_151309-2p64vwh8\files\wandb-metadata.json wandb-metadata.json
2024-03-06 15:17:56,077 INFO    SenderThread:47720 [dir_watcher.py:finish():380] scan save: .\wandb\run-20240306_151309-2p64vwh8\files\wandb-summary.json wandb-summary.json
2024-03-06 15:17:56,084 INFO    SenderThread:47720 [sender.py:transition_state():392] send defer: 7
2024-03-06 15:17:56,085 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: defer
2024-03-06 15:17:56,090 INFO    HandlerThread:47720 [handler.py:handle_request_defer():164] handle defer: 7
2024-03-06 15:17:56,091 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: defer
2024-03-06 15:17:56,092 INFO    SenderThread:47720 [sender.py:send_request_defer():388] handle sender defer: 7
2024-03-06 15:17:56,092 INFO    SenderThread:47720 [file_pusher.py:finish():145] shutting down file pusher
2024-03-06 15:17:56,096 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,097 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,203 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,204 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,311 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,312 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,421 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,422 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,530 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,531 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,638 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,639 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,747 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,747 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
2024-03-06 15:17:56,854 DEBUG   HandlerThread:47720 [handler.py:handle_request():141] handle_request: poll_exit
2024-03-06 15:17:56,855 DEBUG   SenderThread:47720 [sender.py:send_request():249] send_request: poll_exit
